# Generated by Django 4.1 on 2022-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='General_Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ladies_Wing_Presint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organizing_Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Quest', models.CharField(max_length=250)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Ladies Wing Presint', 'Ladies Wing Presint'), ('General Secretary', 'General Secretary'), ('Financial Secretary', 'Financial Secretary'), ('Organizing Secretary', 'Organizing Secre')], max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vice_President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('Name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count_1', models.IntegerField(default=0)),
                ('count_2', models.IntegerField(default=0)),
            ],
        ),
    ]
