# Generated by Django 4.1 on 2022-08-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Financial_Secretary',
        ),
        migrations.DeleteModel(
            name='General_Secretary',
        ),
        migrations.DeleteModel(
            name='Ladies_Wing_Presint',
        ),
        migrations.DeleteModel(
            name='Organizing_Secretary',
        ),
        migrations.DeleteModel(
            name='President',
        ),
        migrations.DeleteModel(
            name='Vice_President',
        ),
        migrations.AddField(
            model_name='poll',
            name='Name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='Name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='count_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='count_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='poll',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
