# Generated by Django 4.1 on 2022-08-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_delete_financial_secretary_delete_general_secretary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Ladies Wing President', 'Ladies Wing President'), ('General Secretary', 'General Secretary'), ('Financial Secretary', 'Financial Secretary'), ('Organizing Secretary', 'Organizing Secretary')], max_length=200),
        ),
    ]
